name: Acceptance Cycle
run-name: Acceptance Cycle

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      runner:
        description: "Runner Agent"
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - self-hosted
  workflow_run:
    workflows: [ "Commit Cycle" ]
    types:
      - completed

jobs:
  run_test:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'}}
    runs-on: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.runner || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v5
        with:
          ref: develop

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.7

      - name: Run integration tests
        run: echo "Running integration tests ðŸ§ª"
      #        run: flutter test test/integrations

      - name: Run component tests
        run: echo "Running component tests ðŸ§ª"
#        run: flutter test test/components
